### ISSUE TITLE
two questions need help

### ISSUE THREAD

**Issue by shenliu27** [HUAnalytics/ANLY580-90-2016#5]
1. When I •Add a connection to the original owner’s repository, I could type `$ git remote add myfriend git://github.com/myfriend/the_repo` in the directory I want, correct? So if I `$ git pull`in this directory, I will get updated file from original repository, right?
2. My Rstudio doesn't work after I try to use version control. Now it is total blank after opening. Only top menu bar left but not working. I have tried uninstall R and Rstudio, then reinstall them. Problem still happens. Any opinions? Appreciate that!

**Comment by kpurcell** [comment]
You will have to be more specific about "Rstudio not working" does it crash? or fail to load R?  I was able to merge your code so I am assuming you solved question 1.  If both of these have been worked out then close the issue.  If not, clarify your Rstudio issues

**Comment by shenliu27** [comment]
nope, I "edit" the rmd file with R. Currently, when I double click the Rstudio icon to start it, it shows
![rstudio openning](https://cloud.githubusercontent.com/assets/19178357/15296336/ef044a2a-1b62-11e6-8045-5c982bd0bd20.jpg)

And I try to run diagnostics, it stays 
![run diag](https://cloud.githubusercontent.com/assets/19178357/15296459/6ff24682-1b63-11e6-877b-3481ef7d387d.jpg)

**Comment by shenliu27** [comment]
finally, I found the solution, just uninstall Git. Seems there is some conflict between Rstudio and Git. Thanks Google.
